### ISSUE TITLE
SSR compatibility broken

### ISSUE THREAD

**Issue by jonadeline** [andsala/svelte-persistent-store#9]
Hi,

Since the release of 0.1.4 it seems that this component is not compatible with SSR/Universal rendering (with sapper) any longer. 
A reference to `window.localStorage` is generated in the `server.js` causing an error as the window object doesn't exist server side. 

Rolling back to 0.1.3 fix the issue.

**Comment by edjw** [comment]
I had the same issue with 0.1.4 and installing 0.1.3 instead also fixed the issue

**Comment by mochi-co** [comment]
I also have this issue, downgrading to 0.1.3 resolves the issue.

**Comment by SillyFreak** [comment]
The problem is very obviously [here](https://github.com/sillyfreak/svelte-persistent-store/commit/3f21c3b4bbc529b9fc10886c08153bde6935ae9a) in `src/local.ts` and `src/session.ts`. @andsala would you appreciate a PR reverting the relevant changes, or was that change intentional but the build pipeline didn't do whatever it was intended to do?

**Comment by andsala** [comment]
I'm not using much Svelte lately so I'd love PRs to fix the issues
